version: '2'
services:
  db:
    image: postgres:9.4.1
    ports:
      - "5432:5432"

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - .:/app

  proxy:
    image: haproxy:1.5
    volumes:
       - "./haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg"
    depends_on:
       - web
    ports:
       - "80:80"
       - "70:70"
    expose:
      - "80"
      - "70"   
